version: "3"

# Services
services:
  solid:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./data:/data
      - ./custom.json:/community-server/custom.json
    command: -c /community-server/custom.json -f /data
    ports:
      - "3000:3000"

