version: "3"

# Services
services:
  solid:
    image: solidproject/community-server:edge  # :6.0.1
    restart: always
    volumes:
      - ./data:/data
      - ./custom-link-rel.json:/community-server/custom-link-rel.json
    command: -c /community-server/custom-link-rel.json -f /data
    ports:
      - "3000:3000"

